// Map<String, String> flagCodes = {
//   "Andorra": "AD",
//   "United Arab Emirates": "AE",
//   "Afghanistan": "AF",
//   "Antigua and Barbuda": "AG",
//   "Anguilla": "AI",
//   "Albania": "AL",
//   "Armenia": "AM",
//   "Netherlands Antilles": "AN",
//   "Angola": "AO",
//   "Antarctica": "AQ",
//   "Argentina": "AR",
//   "American Samoa": "AS",
//   "Austria": "AT",
//   "Australia": "AU",
//   "Aruba": "AW",
//   "Åland Islands": "AX",
//   "Azerbaijan": "AZ",
//   "Azerbaijan": "AZ",
//   "Bosnia and Herzegovina": "BA",
//   "Barbados": "BB",
//   "Bangladesh": "BD",
//   "Belgium": "BE",
//   "Burkina Faso": "BF",
//   "Bulgaria": "BG",
//   "Bahrain": "BH",
//   "Burundi": "BI",
//   "Benin": "BJ",
//   "Saint Barthelemy": "BL",
//   "Saint Barthélemy": "BL",
//   "Bermuda": "BM",
//   //"Brunei Darussalam": "BN",
//   "Brunei": "BN",
//   //"Bolivia, Plurinational State of": "BO",
//   "Bolivia": "BO",
//   "Caribbean Netherlands": "BQ",
//   "Brazil": "BR",
//   "Bahamas": "BS",
//   "Bahamas, The": "BS",
//   "The Bahamas": "BS",
//   "Bhutan": "BT",
//   "Bouvet Island": "BV",
//   "Botswana": "BW",
//   "Belarus": "BY",
//   "Belize": "BZ",
//   "Canada": "CA",
//   "Cocos (Keeling) Islands": "CC",
//   "Congo, the Democratic Republic of the": "CD",
//   "Congo (Brazzaville)": "CD",
//   "Republic of the Congo": "CD",
//   "Central African Republic": "CF",
//   "Congo": "CG",
//   "Congo (Kinshasa)": "CG",
//   "Switzerland": "CH",
//   "Côte d'Ivoire": "CI",
//   "Cote d'Ivoire": "CI",
//   "Ivory Coast": "CI",
//   "Cook Islands": "CK",
//   "Chile": "CL",
//   "Cameroon": "CM",
//   "China": "CN",
//   "Colombia": "CO",
//   "Costa Rica": "CR",
//   "Cuba": "CU",
//   "Cape Verde": "CV",
//   "Cabo Verde": "CV",
//   "Curaçao": "CW",
//   "Curacao": "CW",
//   "Christmas Island": "CX",
//   "Cyprus": "CY",
//   "Czech Republic": "CZ",
//   "Czechia": "CZ",
//   "Germany": "DE",
//   "Djibouti": "DJ",
//   "Denmark": "DK",
//   "Dominica": "DM",
//   "Dominican Republic": "DO",
//   "Algeria": "DZ",
//   "Ecuador": "EC",
//   "Estonia": "EE",
//   "Egypt": "EG",
//   "Western Sahara": "EH",
//   "Eritrea": "ER",
//   "Spain": "ES",
//   "Ethiopia": "ET",
//   "Europe": "EU",
//   "Finland": "FI",
//   "Fiji": "FJ",
//   "Falkland Islands (Malvinas)": "FK",
//   "Micronesia, Federated States of": "FM",
//   "Faroe Islands": "FO",
//   "France": "FR",
//   "Gabon": "GA",
//   "England": "GB-ENG",
//   "Diamond Princess": "GB-ENG",
//   "Northern Ireland": "GB-NIR",
//   "North Ireland": "GB-NIR",
//   "Scotland": "GB-SCT",
//   "Wales": "GB-WLS",
//   "United Kingdom": "GB",
//   "Grenada": "GD",
//   "Georgia": "GE",
//   "French Guiana": "GF",
//   "Guernsey": "GG",
//   "Ghana": "GH",
//   "Gibraltar": "GI",
//   "Greenland": "GL",
//   "Gambia": "GM",
//   "The Gambia": "GM",
//   "Gambia, The": "GM",
//   "Guinea": "GN",
//   "Guadeloupe": "GP",
//   "Equatorial Guinea": "GQ",
//   "Greece": "GR",
//   "South Georgia and the South Sandwich Islands": "GS",
//   "Guatemala": "GT",
//   "Guam": "GU",
//   "Guinea-Bissau": "GW",
//   "Guyana": "GY",
//   "Hong Kong": "HK",
//   "Hong Kong SAR": "HK",
//   "Heard Island and McDonald Islands": "HM",
//   "Honduras": "HN",
//   "Croatia": "HR",
//   "Haiti": "HT",
//   "Hungary": "HU",
//   "Indonesia": "ID",
//   "Ireland": "IE",
//   "Republic of Ireland": "IE",
//   "Israel": "IL",
//   "occupied Palestinian territory": "IL",
//   "Isle of Man": "IM",
//   "India": "IN",
//   "British Indian Ocean Territory": "IO",
//   "Iraq": "IQ",
//   "Iran (Islamic Republic of)": "IR",
//   "Iran": "IR",
//   "Iceland": "IS",
//   "Italy": "IT",
//   "Jersey": "JE",
//   "Cruise Ship" : "AQ",
//   "Channel Islands": "JE",
//   "Jamaica": "JM",
//   "Jordan": "JO",
//   "Japan": "JP",
//   "Kenya": "KE",
//   "Kyrgyzstan": "KG",
//   "Cambodia": "KH",
//   "Kiribati": "KI",
//   "Comoros": "KM",
//   "Saint Kitts and Nevis": "KN",
//   "Korea, Democratic People's Republic of": "KP",
//   "Republic of Korea": "KP",
//   "Korea, Republic of": "KR",
//   "Korea, South": "KR",
//   "South Korea": "KR",
//   "Kuwait": "KW",
//   "Cayman Islands": "KY",
//   "Kazakhstan": "KZ",
//   "Lao People's Democratic Republic": "LA",
//   "Laos": "LA",
//   "Lebanon": "LB",
//   "Saint Lucia": "LC",
//   "Liechtenstein": "LI",
//   "Sri Lanka": "LK",
//   "Liberia": "LR",
//   "Lesotho": "LS",
//   "Lithuania": "LT",
//   "Luxembourg": "LU",
//   "Latvia": "LV",
//   "Libya": "LY",
//   "Morocco": "MA",
//   "Monaco": "MC",
//   "Moldova, Republic of": "MD",
//   "Republic of Moldova": "MD",
//   "Moldova": "MD",
//   "Montenegro": "ME",
//   "Saint Martin": "MF",
//   "St. Martin": "MF",
//   "Madagascar": "MG",
//   "Marshall Islands": "MH",
//   "Macedonia, the former Yugoslav Republic of": "MK",
//   "North Macedonia": "MK",
//   "Mali": "ML",
//   "Myanmar": "MM",
//   "Burma": "MM",
//   "Mongolia": "MN",
//   "Macao": "MO",
//   "Macau": "MO",
//   "Macao SAR": "MO",
//   "Northern Mariana Islands": "MP",
//   "Martinique": "MQ",
//   "Mauritania": "MR",
//   "Montserrat": "MS",
//   "Malta": "MT",
//   "Mauritius": "MU",
//   "Maldives": "MV",
//   "Malawi": "MW",
//   "Mexico": "MX",
//   "Malaysia": "MY",
//   "Mozambique": "MZ",
//   "Namibia": "NA",
//   "New Caledonia": "NC",
//   "Niger": "NE",
//   "Norfolk Island": "NF",
//   "Nigeria": "NG",
//   "Nicaragua": "NI",
//   "Netherlands": "NL",
//   "MS Zaandam": "NL",
//   "Norway": "NO",
//   "Nepal": "NP",
//   "Nauru": "NR",
//   "Niue": "NU",
//   "New Zealand": "NZ",
//   "Oman": "OM",
//   "Panama": "PA",
//   "Peru": "PE",
//   "French Polynesia": "PF",
//   "Papua New Guinea": "PG",
//   "Philippines": "PH",
//   "Pakistan": "PK",
//   "Poland": "PL",
//   "Saint Pierre and Miquelon": "PM",
//   "Pitcairn": "PN",
//   "Puerto Rico": "PR",
//   "Palestine": "PS",
//   "West Bank and Gaza": "PS",
//   "Portugal": "PT",
//   "Palau": "PW",
//   "Paraguay": "PY",
//   "Qatar": "QA",
//   "Réunion": "RE",
//   "Reunion": "RE",
//   "Romania": "RO",
//   "Serbia": "RS",
//   "Russian Federation": "RU",
//   "Russia": "RU",
//   "Rwanda": "RW",
//   "Saudi Arabia": "SA",
//   "Solomon Islands": "SB",
//   "Seychelles": "SC",
//   "Sudan": "SD",
//   "Sweden": "SE",
//   "Singapore": "SG",
//   "Saint Helena, Ascension and Tristan da Cunha": "SH",
//   "Slovenia": "SI",
//   "Svalbard and Jan Mayen Islands": "SJ",
//   "Slovakia": "SK",
//   "Sierra Leone": "SL",
//   "San Marino": "SM",
//   "Senegal": "SN",
//   "Somalia": "SO",
//   "Suriname": "SR",
//   "South Sudan": "SS",
//   "Sao Tome and Principe": "ST",
//   "El Salvador": "SV",
//   "Sint Maarten (Dutch part)": "SX",
//   "Syrian Arab Republic": "SY",
//   "Syria": "SY",
//   "Swaziland": "SZ",
//   "Turks and Caicos Islands": "TC",
//   "Chad": "TD",
//   "French Southern Territories": "TF",
//   "Togo": "TG",
//   "Thailand": "TH",
//   "Tajikistan": "TJ",
//   "Tokelau": "TK",
//   "Timor-Leste": "TL",
//   "East Timor": "TL",
//   "Turkmenistan": "TM",
//   "Tunisia": "TN",
//   "Tonga": "TO",
//   "Turkey": "TR",
//   "Trinidad and Tobago": "TT",
//   "Tuvalu": "TV",
//   "Taiwan": "TW",
//   "Taiwan*": "TW",
//   "Taipei and environs": "TW",
//   "Tanzania, United Republic of": "TZ",
//   "Tanzania": "TZ",
//   "Ukraine": "UA",
//   "Uganda": "UG",
//   "US Minor Outlying Islands": "UM",
//   "United States": "US",
//   "US": "US",
//   "Uruguay": "UY",
//   "Uzbekistan": "UZ",
//   "Holy See (Vatican City State)": "VA",
//   "Vatican City": "VA",
//   "Holy See": "VA",
//   "Saint Vincent and the Grenadines": "VC",
//   "Venezuela, Bolivarian Republic of": "VE",
//   "Venezuela": "VE",
//   "Virgin Islands, British": "VG",
//   "Virgin Islands, U.S.": "VI",
//   "Viet Nam": "VN",
//   "Vietnam": "VN",
//   "Vanuatu": "VU",
//   "Wallis and Futuna Islands": "WF",
//   "Kosovo": "XK",
//   "Samoa": "WS",
//   "Yemen": "YE",
//   "Mayotte": "YT",
//   "South Africa": "ZA",
//   "Eswatini": "ZA",
//   "Zambia": "ZM",
//   "Zimbabwe": "ZW",
//   "Others" : "AQ"
// };

Map<String,String> flagCodes = {
  "AD": "Andorra",
  "AE": "United Arab Emirates",
  "AF": "Afghanistan",
  "AG": "Antigua and Barbuda",
  "AI": "Anguilla",
  "AL": "Albania",
  "AM": "Armenia",
  "AN": "Netherlands Antilles",
  "AO": "Angola",
  "AQ": "Antarctica",
  "AR": "Argentina",
  "AS": "American Samoa",
  "AT": "Austria",
  "AU": "Australia",
  "AW": "Aruba",
  "AX": "\u00c5land Islands",
  "AZ": "Azerbaijan",
  "BA": "Bosnia and Herzegovina",
  "BB": "Barbados",
  "BD": "Bangladesh",
  "BE": "Belgium",
  "BF": "Burkina Faso",
  "BG": "Bulgaria",
  "BH": "Bahrain",
  "BI": "Burundi",
  "BJ": "Benin",
  "BL": "Saint Barthélemy",
  "BM": "Bermuda",
  "BN": "Brunei Darussalam",
  "BO": "Bolivia, Plurinational State of",
  "BQ": "Caribbean Netherlands",
  "BR": "Brazil",
  "BS": "Bahamas",
  "BT": "Bhutan",
  "BV": "Bouvet Island",
  "BW": "Botswana",
  "BY": "Belarus",
  "BZ": "Belize",
  "CA": "Canada",
  "CC": "Cocos (Keeling) Islands",
  "CD": "Congo, the Democratic Republic of the",
  "CF": "Central African Republic",
  "CG": "Congo",
  "CH": "Switzerland",
  "CI": "C\u00f4te d'Ivoire",
  "CK": "Cook Islands",
  "CL": "Chile",
  "CM": "Cameroon",
  "CN": "China",
  "CO": "Colombia",
  "CR": "Costa Rica",
  "CU": "Cuba",
  "CV": "Cape Verde",
  "CW": "Cura\u00e7ao",
  "CX": "Christmas Island",
  "CY": "Cyprus",
  "CZ": "Czech Republic",
  "DE": "Germany",
  "DJ": "Djibouti",
  "DK": "Denmark",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "DZ": "Algeria",
  "EC": "Ecuador",
  "EE": "Estonia",
  "EG": "Egypt",
  "EH": "Western Sahara",
  "ER": "Eritrea",
  "ES": "Spain",
  "ET": "Ethiopia",
  "EU": "Europe",
  "FI": "Finland",
  "FJ": "Fiji",
  "FK": "Falkland Islands (Malvinas)",
  "FM": "Micronesia, Federated States of",
  "FO": "Faroe Islands",
  "FR": "France",
  "GA": "Gabon",
  "GB-ENG": "England",
  "GB-NIR": "Northern Ireland",
  "GB-SCT": "Scotland",
  "GB-WLS": "Wales",
  "GB": "United Kingdom",
  "GD": "Grenada",
  "GE": "Georgia",
  "GF": "French Guiana",
  "GG": "Guernsey",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GL": "Greenland",
  "GM": "Gambia",
  "GN": "Guinea",
  "GP": "Guadeloupe",
  "GQ": "Equatorial Guinea",
  "GR": "Greece",
  "GS": "South Georgia and the South Sandwich Islands",
  "GT": "Guatemala",
  "GU": "Guam",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HK": "Hong Kong",
  "HM": "Heard Island and McDonald Islands",
  "HN": "Honduras",
  "HR": "Croatia",
  "HT": "Haiti",
  "HU": "Hungary",
  "ID": "Indonesia",
  "IE": "Ireland",
  "IL": "Israel",
  "IM": "Isle of Man",
  "IN": "India",
  "IO": "British Indian Ocean Territory",
  "IQ": "Iraq",
  "IR": "Iran, Islamic Republic of",
  "IS": "Iceland",
  "IT": "Italy",
  "JE": "Jersey",
  "JM": "Jamaica",
  "JO": "Jordan",
  "JP": "Japan",
  "KE": "Kenya",
  "KG": "Kyrgyzstan",
  "KH": "Cambodia",
  "KI": "Kiribati",
  "KM": "Comoros",
  "KN": "Saint Kitts and Nevis",
  "KP": "Korea, Democratic People's Republic of",
  "KR": "Korea, Republic of",
  "KW": "Kuwait",
  "KY": "Cayman Islands",
  "KZ": "Kazakhstan",
  "LA": "Lao People's Democratic Republic",
  "LB": "Lebanon",
  "LC": "Saint Lucia",
  "LI": "Liechtenstein",
  "LK": "Sri Lanka",
  "LR": "Liberia",
  "LS": "Lesotho",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "LV": "Latvia",
  "LY": "Libya",
  "MA": "Morocco",
  "MC": "Monaco",
  "MD": "Moldova, Republic of",
  "ME": "Montenegro",
  "MF": "Saint Martin",
  "MG": "Madagascar",
  "MH": "Marshall Islands",
  "MK": "Macedonia, the former Yugoslav Republic of",
  "ML": "Mali",
  "MM": "Myanmar",
  "MN": "Mongolia",
  "MO": "Macao",
  "MP": "Northern Mariana Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MS": "Montserrat",
  "MT": "Malta",
  "MU": "Mauritius",
  "MV": "Maldives",
  "MW": "Malawi",
  "MX": "Mexico",
  "MY": "Malaysia",
  "MZ": "Mozambique",
  "NA": "Namibia",
  "NC": "New Caledonia",
  "NE": "Niger",
  "NF": "Norfolk Island",
  "NG": "Nigeria",
  "NI": "Nicaragua",
  "NL": "Netherlands",
  "NO": "Norway",
  "NP": "Nepal",
  "NR": "Nauru",
  "NU": "Niue",
  "NZ": "New Zealand",
  "OM": "Oman",
  "PA": "Panama",
  "PE": "Peru",
  "PF": "French Polynesia",
  "PG": "Papua New Guinea",
  "PH": "Philippines",
  "PK": "Pakistan",
  "PL": "Poland",
  "PM": "Saint Pierre and Miquelon",
  "PN": "Pitcairn",
  "PR": "Puerto Rico",
  "PS": "Palestine",
  "PT": "Portugal",
  "PW": "Palau",
  "PY": "Paraguay",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Romania",
  "RS": "Serbia",
  "RU": "Russian Federation",
  "RW": "Rwanda",
  "SA": "Saudi Arabia",
  "SB": "Solomon Islands",
  "SC": "Seychelles",
  "SD": "Sudan",
  "SE": "Sweden",
  "SG": "Singapore",
  "SH": "Saint Helena, Ascension and Tristan da Cunha",
  "SI": "Slovenia",
  "SJ": "Svalbard and Jan Mayen Islands",
  "SK": "Slovakia",
  "SL": "Sierra Leone",
  "SM": "San Marino",
  "SN": "Senegal",
  "SO": "Somalia",
  "SR": "Suriname",
  "SS": "South Sudan",
  "ST": "Sao Tome and Principe",
  "SV": "El Salvador",
  "SX": "Sint Maarten (Dutch part)",
  "SY": "Syrian Arab Republic",
  "SZ": "Swaziland",
  "TC": "Turks and Caicos Islands",
  "TD": "Chad",
  "TF": "French Southern Territories",
  "TG": "Togo",
  "TH": "Thailand",
  "TJ": "Tajikistan",
  "TK": "Tokelau",
  "TL": "Timor-Leste",
  "TM": "Turkmenistan",
  "TN": "Tunisia",
  "TO": "Tonga",
  "TR": "Turkey",
  "TT": "Trinidad and Tobago",
  "TV": "Tuvalu",
  "TW": "Taiwan",
  "TZ": "Tanzania, United Republic of",
  "UA": "Ukraine",
  "UG": "Uganda",
  "UM": "US Minor Outlying Islands",
  "US": "United States",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VA": "Holy See (Vatican City State)",
  "VC": "Saint Vincent and the Grenadines",
  "VE": "Venezuela, Bolivarian Republic of",
  "VG": "Virgin Islands, British",
  "VI": "Virgin Islands, U.S.",
  "VN": "Viet Nam",
  "VU": "Vanuatu",
  "WF": "Wallis and Futuna Islands",
  "XK": "Kosovo",
  "WS": "Samoa",
  "YE": "Yemen",
  "YT": "Mayotte",
  "ZA": "South Africa",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
};